#################################################################
# Investigación ElasticSearch | Bases de Datos II  #            #
#        Primer Semestre 2022 | ITCR               #    Fecha   #    
# Autores: Gabriela Gutiérrez, Allison Montero,    # 28/04/2022 #
#            Francisco Chavarro, Diego Masis       #            #
#################################################################

#Required Libraries
from elasticsearch import Elasticsearch
from datetime import datetime
from pprint import pprint
import json
import warnings

#Avoid warning messages
warnings.filterwarnings("ignore")

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "k2eho9xOtlFVXExJJ6YFz2Zp"

# Found in thclse 'Manage Deployment' page
CLOUD_ID = "Prototipo:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvJDNiZDU1MzllZjVmZTRmOGY4NGQ5YTNjZDgzYmViZGQ2JGIyMjdiNmVkYzdmNzQxZTdhZjNlZmNmODcxNzFiNTk5"

# Create the client instance
client = Elasticsearch(
    cloud_id=CLOUD_ID, #Using the cloud id we get from the website
    basic_auth=("elastic", ELASTIC_PASSWORD), #Using the password we get from the website
    ca_certs= False,
    verify_certs= False
)


#Opening JSON files to index with ElasticSearch
with open("C:\\Users\\amtme\\Downloads\\sample1.json") as f:
    json1 = json.loads(f.read())

with open("C:\\Users\\amtme\\Downloads\\sample2.json") as f:
    json2 = json.loads(f.read())


# Creating index and indexing first JSON doc
resp = client.index(index="personas-index", id=1, document= json1) #We provide a different id to each document
print("\n***Primer Documento*** ")
print(resp['result'])
print("\n")

#Indexing the second JSON doc
resp = client.index(index="personas-index", id=2, document= json2) #We provide a different id to each document
print("\n***Segundo Documento*** ")
print(resp['result'])
print("\n")


#Get the documents
print("Recuperación del documento 1\n")
resp = client.get(index="personas-index", id=1)
print(resp['_source'])


#Search for specific data, gender=male
print("\nBúsqueda de documentos en donde sexo=masculino")
body = {'query': {'bool': {'must': [{'match': {'gender': 'female'}}]}}}
res = client.search(index='personas-index', body=body)
pprint(res)

#Delete the document
#client.delete(index="test-index", id=1)